### ISSUE TITLE
eHZ-PW8E2A6L0HQ2D Unable to parse SML from response

### ISSUE THREAD

**Issue by SpiGAndromeda** [micw/tibber-pulse-reader#15]
Hi I just installed the Tibber Pulse on my new electric meter. Data is transmitted to Tibber just fine.

However, the reader cannot parse the transmitted data. I already extracted some data via NodeRED with a buffer parser but that was not reliable. In NodeRED I saw that the length of the message varies. Sometimes it's 252, sometimes it's 256. You're pulse reader couldn't interpret either, so I guess the SML data is not standards-compliant.

CRC error are ignored. (I also tested it with enabled CRC check)

This is the data from the debug mode:
`1b1b1b1b0101010176050013f6ff6200620072630101760107ffffffffffff050006a7ab0b0a01454d480000c312a17262016406aea2620163b7fa0076050013f70062006200726307017707ffffffffffff0b0a01454d480000c312a1070100620affff7262016406aea27577070100603201010101010104454d480177070100600100ff010101010b0a01454d480000c312a10177070100010800ff640801047262016406aea2621e52ff6403e05a0177070100020800ff017262016406aea2621e52ff6367540177070100100700ff0101621b520052240101016305eb0076050013f7016200620072630201710163fd5c001b1b1b1b1a000d95`

The stack trace:
```
java.lang.RuntimeException: Expected UNSIGNED of length 4 but found UNSIGNED_24: 437922
tipper-pulse-reader  |  at de.wyraz.sml.asn1.ASN1BERTokenizer.expect(ASN1BERTokenizer.java:226) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.asn1.ASN1BERTokenizer.readNext(ASN1BERTokenizer.java:215) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.asn1.ASN1BERTokenizer.readUnsigned32(ASN1BERTokenizer.java:198) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.SMLMessageParser.parseSMLTime(SMLMessageParser.java:193) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.SMLMessageParser.parseSMLPublicOpenResponse(SMLMessageParser.java:92) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.SMLMessageParser.parseSMLMessageBody(SMLMessageParser.java:72) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.SMLMessageParser.parseSMLMessages(SMLMessageParser.java:54) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.sml.SMLMessageParser.parse(SMLMessageParser.java:31) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.tibberpulse.sml.SMLDecoder.decode(SMLDecoder.java:64) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.tibberpulse.source.TibberPulseHttpReader.fetch(TibberPulseHttpReader.java:86) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at de.wyraz.tibberpulse.source.TibberPulseHttpReader.run(TibberPulseHttpReader.java:51) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:817) ~[spring-boot-2.5.14.jar!/:2.5.14]
tipper-pulse-reader  |  at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:801) ~[spring-boot-2.5.14.jar!/:2.5.14]
tipper-pulse-reader  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:350) ~[spring-boot-2.5.14.jar!/:2.5.14]
tipper-pulse-reader  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) ~[spring-boot-2.5.14.jar!/:2.5.14]
tipper-pulse-reader  |  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) ~[spring-boot-2.5.14.jar!/:2.5.14]
tipper-pulse-reader  |  at de.wyraz.tibberpulse.TibberPulseReader.main(TibberPulseReader.java:18) ~[classes!/:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
tipper-pulse-reader  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
tipper-pulse-reader  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
tipper-pulse-reader  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
tipper-pulse-reader  |  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[tibber-pulse-reader.jar:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[tibber-pulse-reader.jar:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[tibber-pulse-reader.jar:1.0.0-SNAPSHOT]
tipper-pulse-reader  |  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[tibber-pulse-reader.jar:1.0.0-SNAPSHOT]
```

The model is in the title of this issue. I attach the manual of the electric meter. The ORBIS codes that the SML response should contain are on the pages 11 and 12. My electric meter works "saldierend", so only `01 00 01 08 00 FF`, `01 00 02 08 00 FF` and `01 00 10 07 00 FF` should be contained in the SML Response.

[bedienungsanleitung-emh-ehz-p.pdf](https://github.com/micw/tibber-pulse-reader/files/11786759/bedienungsanleitung-emh-ehz-p.pdf)

P.S. this is a great project!

**Comment by micw** [comment]
Hello,
a while ago I have started to add workarounds for some buggy meters from https://github.com/devZer0/libsml-testing. Seems that your's was also there, with my local version it works.
I have committed my latest changes and added a test for your meter. Should work with the latest build.

Please test and close the issue if it's fixed for you.
